# Generated by Django 5.1 on 2025-04-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='authorized_capital',
            field=models.CharField(default='10 000 руб.', max_length=50, verbose_name='Уставный капитал'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='inn',
            field=models.CharField(default='5402068150', max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='kpp',
            field=models.CharField(default='1215400031714', max_length=20, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='legal_address',
            field=models.TextField(default='630001, Новосибирская область, г Новосибирск, Владимировская ул, зд. 26/1, этаж 5 офис 504', verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='ogrn',
            field=models.CharField(default='1215400031714', max_length=13, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='registration_date',
            field=models.DateField(default='2021-07-26', verbose_name='Дата регистрации'),
        ),
    ]
