# Generated by Django 5.1 on 2025-04-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_companyinfo_authorized_capital_companyinfo_inn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=18, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('photo', models.ImageField(upload_to='contacts/managers/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
    ]
