# Generated by Django 5.1 on 2025-04-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactsmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(default='г.Владивосток, ул. Днепровская, д.25д, стр.4а', max_length=200, verbose_name='Адрес'),
        ),
    ]
