# Generated by Django 5.1 on 2025-04-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_partners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
    ]
