# Generated by Django 5.1 on 2025-04-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_rename_partners_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='photo',
            new_name='logo',
        ),
    ]
