# Generated by Django 5.1 on 2024-11-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_registrationrequest_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='to_save',
            field=models.BooleanField(default=False, verbose_name='Зарегистрировать?'),
        ),
    ]
