# Generated by Django 5.1 on 2024-11-08 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_registrationrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
    ]
