# Generated by Django 5.1 on 2024-11-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_id_in_amocrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
    ]
