# Generated by Django 5.1 on 2024-11-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_registrationrequest_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
