# Generated by Django 5.1 on 2024-11-20 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_city_options_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.city', verbose_name='Город'),
        ),
    ]
