# Generated by Django 5.1 on 2024-11-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_registrationrequest_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Фамилия'),
        ),
    ]
