# Generated by Django 5.1 on 2024-11-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_registrationrequest_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='last_name',
            field=models.CharField(default=' ', max_length=50, verbose_name='Фамилия'),
        ),
    ]
