# Generated by Django 5.1 on 2025-02-26 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_city'),
        ('users', '0016_alter_registrationrequest_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='user',
            name='legal_entity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юр. лицо'),
        ),
        migrations.AddField(
            model_name='user',
            name='priority_transport_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliveryterm', verbose_name='Приоритетная ТК'),
        ),
        migrations.AddField(
            model_name='user',
            name='requisites',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Реквизиты'),
        ),
    ]
