# Generated by Django 5.1 on 2025-05-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='requisites',
        ),
    ]
