# Generated by Django 5.1 on 2025-05-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_user_legal_entity_user_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Полный адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='user',
            name='kpp',
            field=models.IntegerField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
    ]
