# Generated by Django 5.1 on 2025-05-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_full_address_user_inn_user_kpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
    ]
