services:
  db:
    image: postgres:15-alpine
    container_name: database
    environment:
      - POSTGRES_DB=aleucos
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - dev

  redis:
    image: redis:alpine
    networks:
      - dev

  elasticsearch: 
    image: elasticsearch:8.7.1
    container_name: elasticsearch 
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
      - network.host=0.0.0.0
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    networks:
      - dev

  backend: 
    build: . 
    entrypoint: /entrypoint.sh
    ports: 
      - "8000:8000"
      - "5555:5555"
    depends_on:
      - db
      - redis
      - elasticsearch
    volumes:
      - ./media:/media
    networks:
      - dev

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - dev


networks:
  dev: