version: "3"

services:
  db:
    image: postgres:15-alpine
    container_name: database
    environment:
      - POSTGRES_DB=aleucos
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    # networks:
    #   - dev
    ports:
      - "5433:5433"
    command: ["postgres", "-p", "5433"]

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - dev
    ports:
      - "6379:6379" 

  elasticsearch:
    image: elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - network.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    networks:
      - dev
    ports:
      - "9200:9200"  
      - "9300:9300" 

  kibana:
    image: kibana:8.7.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - dev

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - dev
    depends_on:
      - elasticsearch


networks:
  dev:
