# Generated by Django 5.1 on 2024-10-31 09:11

import configs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_catalog_filename', models.CharField(default='catalog.xlsx', help_text='Название, под которым сохраняется Excel-файл с каталогом при импорте', max_length=150, verbose_name='IMPORT_CATALOG_FILENAME')),
                ('export_catalog_filename', models.CharField(default='catalog_for_export.xlsx', help_text='Название Excel-файла с экспортированным каталогом', max_length=150, verbose_name='EXPORT_CATALOG_FILENAME')),
                ('export_catalog_template_filename', models.CharField(default='catalog_template.xlsx', help_text='Название Excel-файла-шаблона для экспорта каталога', max_length=150, verbose_name='EXPORT_CATALOG_TEMPLATE_FILENAME')),
                ('order_status_name_mapper', models.JSONField(default=configs.models.get_default_order_status_name_mapper, help_text='JSON для соответствия статусов сделок и заказов. { статус_сделки: статус_заказа, ... }', verbose_name='ORDER_STATUS_NAME_CONVERTER')),
                ('order_status_first', models.CharField(default='В обработке', help_text='Первый статус заказа в базе данных', verbose_name='ORDER_STATUS_FIRST')),
                ('lead_status_first', models.CharField(default='Клиент прислал заказ', help_text='Первый статус сделки, с которого начинается путь заказа', verbose_name='LEAD_STATUS_FIRST')),
                ('lead_status_last', models.CharField(default='Успешно реализовано', help_text='Последний статус сделки', verbose_name='LEAD_STATUS_LAST')),
                ('admins_group_name', models.CharField(default='Administrators', help_text='Название группы для администраторов', verbose_name='ADMINS_GROUP_NAME')),
                ('managers_group_name', models.CharField(default='Managers', help_text='Название группы для менеджеров', verbose_name='MANAGERS_GROUP_NAME')),
                ('users_group_name', models.CharField(default='Users', help_text='Название группы для зарегистрированных пользователей', verbose_name='USERS_GROUP_NAME')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
