# Generated by Django 5.1 on 2024-10-31 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Configs',
        ),
    ]
