# Generated by Django 5.1 on 2024-11-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0004_config_head_of_sales_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='title',
            field=models.CharField(default='Настройки', verbose_name='Настройки'),
        ),
    ]
