# Generated by Django 5.1 on 2024-11-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0005_config_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='title',
            field=models.CharField(default='Настройки', help_text='Название вкладки в админ. панели', verbose_name='Настройки'),
        ),
    ]
