# Generated by Django 5.1 on 2025-04-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0006_alter_config_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='home_page_categories',
            field=models.CharField(default='Уход за волосами, Уход за кожей лица, Декоративная косметика, Для детей', help_text='4 категории, перечисленные через запятую, которые будут отображаться в блоке "Каталог" на главной странице', max_length=150, verbose_name='Категории на главной странице'),
        ),
    ]
