# Generated by Django 5.1 on 2024-09-25 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='managers_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_terms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.deliveryterm', verbose_name='Условия доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.paymentmethod', verbose_name='Способ оплаты'),
        ),
    ]
