# Generated by Django 5.1 on 2024-09-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_manager_alter_order_delivery_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_in_amocrm',
            field=models.BigIntegerField(null=True, verbose_name='ID в amoCRM'),
        ),
    ]
