# Generated by Django 5.1 on 2024-11-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_id_in_amocrm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='brand_name',
            field=models.CharField(blank=True, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
