# Generated by Django 5.1 on 2024-11-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_product_orderitem_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf_bill',
            field=models.FileField(blank=True, null=True, upload_to='orders', verbose_name='Счёт'),
        ),
    ]
