# Generated by Django 5.1 on 2024-11-08 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_pdf_bill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importorderstatus',
            options={'ordering': ['-time'], 'verbose_name': 'Статус импорта заказа', 'verbose_name_plural': 'Статусы импорта заказов'},
        ),
        migrations.RemoveField(
            model_name='importorderstatus',
            name='order',
        ),
        migrations.AddField(
            model_name='importorderstatus',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
            preserve_default=False,
        ),
    ]
