# Generated by Django 5.1 on 2024-11-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_importorderstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importorderstatus',
            options={'ordering': ['-time'], 'verbose_name': 'Статус импорта', 'verbose_name_plural': 'Статус импорта'},
        ),
        migrations.AddField(
            model_name='importorderstatus',
            name='status_type',
            field=models.CharField(choices=[('INFO', 'Информация'), ('PROCESS', 'Обработка'), ('ERROR', 'Ошибка'), ('SUCCESS', 'Успех')], default='INFO', max_length=10, verbose_name='Тип'),
        ),
    ]
