# Generated by Django 5.1 on 2025-03-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pdf_bill',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
    ]
