# Generated by Django 5.1 on 2025-03-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_pdf_bill_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf_bill',
            field=models.FileField(blank=True, null=True, upload_to='orders', verbose_name='Счёт'),
        ),
    ]
