# Generated by Django 5.1 on 2025-04-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_pdf_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='article',
            field=models.CharField(default='', max_length=9, verbose_name='Артикул'),
            preserve_default=False,
        ),
    ]
