# Generated by Django 5.1 on 2025-04-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderitem_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='info_excel',
            field=models.FileField(blank=True, null=True, upload_to='orders/excel/', verbose_name='Информация о заказе (Excel)'),
        ),
    ]
