# Generated by Django 5.1 on 2024-08-22 11:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('barcode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='products')),
                ('volume', models.CharField(max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'Weight cannot be negative')])),
                ('notes', models.CharField(max_length=30)),
                ('price_before_200k', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_after_200k', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_after_500k', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('remains', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand')),
            ],
        ),
    ]
