# Generated by Django 5.1 on 2024-09-24 10:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ImportProductsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Статус импорта товаров',
                'verbose_name_plural': 'Статусы импорта товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.BigIntegerField(verbose_name='Штрихкод')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(default='products/default.png', upload_to='products', verbose_name='Фото')),
                ('volume', models.CharField(max_length=100, null=True, verbose_name='Объём')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'Вес не может быть отрицательным')], verbose_name='Вес')),
                ('notes', models.CharField(blank=True, max_length=30, null=True, verbose_name='Заметки')),
                ('price_before_200k', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена до 200 тыс')),
                ('price_after_200k', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена после 200 тыс')),
                ('price_after_500k', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена после 500 тыс')),
                ('is_in_stock', models.BooleanField(default=False, verbose_name='В наличии')),
                ('remains', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_frozen', models.BooleanField(default=False, verbose_name='Зафиксирован')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-barcode'],
            },
        ),
    ]
