# Generated by Django 5.1 on 2024-10-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-remains'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
