# Generated by Django 5.1 on 2024-08-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
