# Generated by Django 5.1 on 2024-10-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_after_200k',
            field=models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Цена после 200 тыс'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_after_500k',
            field=models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Цена после 500 тыс'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_before_200k',
            field=models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Цена до 200 тыс'),
        ),
    ]
