# Generated by Django 5.1 on 2024-11-07 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_is_frozen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importproductsstatus',
            options={'ordering': ['-time'], 'verbose_name': 'Статус импорта товаров', 'verbose_name_plural': 'Статусы импорта товаров'},
        ),
        migrations.AddField(
            model_name='importproductsstatus',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
            preserve_default=False,
        ),
    ]
