# Generated by Django 5.1 on 2024-11-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_importproductsstatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importproductsstatus',
            name='manager',
        ),
    ]
