# Generated by Django 5.1 on 2024-11-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_importproductsstatus_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='importproductsstatus',
            name='status_type',
            field=models.CharField(choices=[('INFO', 'Информация'), ('ERROR', 'Ошибка'), ('SUCCESS', 'Успех')], default='INFO', max_length=10, verbose_name='Тип'),
        ),
    ]
