# Generated by Django 5.1 on 2024-08-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_description_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.CharField(max_length=100),
        ),
    ]
