# Generated by Django 5.1 on 2024-11-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_importproductsstatus_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importproductsstatus',
            name='status_type',
            field=models.CharField(choices=[('INFO', 'Информация'), ('PROCESS', 'Обработка'), ('ERROR', 'Ошибка'), ('SUCCESS', 'Успех')], default='INFO', max_length=10, verbose_name='Тип'),
        ),
    ]
