# Generated by Django 5.1 on 2024-11-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_importproductsstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
