# Generated by Django 5.1 on 2024-11-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importproductsstatus',
            options={'verbose_name': 'Статус импорта', 'verbose_name_plural': 'Статус импорта'},
        ),
        migrations.RemoveField(
            model_name='importproductsstatus',
            name='time',
        ),
    ]
