# Generated by Django 5.1 on 2024-11-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_importproductsstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importproductsstatus',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-15 00:00', verbose_name='Дата и время'),
            preserve_default=False,
        ),
    ]
