# Generated by Django 5.1 on 2024-11-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_importproductsstatus_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importproductsstatus',
            options={'ordering': ['-pk'], 'verbose_name': 'Статус импорта', 'verbose_name_plural': 'Статус импорта'},
        ),
    ]
