# Generated by Django 5.1 on 2024-09-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-barcode']},
        ),
    ]
