# Generated by Django 5.1 on 2025-02-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_importproductsstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='will_arrive_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прибытия (если в пути)'),
        ),
    ]
