# Generated by Django 5.1 on 2024-09-03 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_importstatus_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='importstatus',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
