# Generated by Django 5.1 on 2025-03-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_will_arrive_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatermarkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('top_left', 'Top Left'), ('top_right', 'Top Right'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right'), ('center', 'Center')], default='bottom_right', max_length=20)),
                ('font_size', models.PositiveIntegerField(default=30)),
                ('text', models.CharField(default='©Aleucos', max_length=255)),
                ('opacity', models.PositiveIntegerField(default=180, help_text='Opacity level (0-255)')),
            ],
        ),
    ]
