# Generated by Django 5.1 on 2025-03-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_watermarkconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermarkconfig',
            name='opacity',
            field=models.PositiveIntegerField(default=180, help_text='Прозрачность (0-255)'),
        ),
    ]
