# Generated by Django 5.1 on 2025-03-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_watermarkconfig_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watermarkconfig',
            options={'verbose_name': 'настройки вотермарки', 'verbose_name_plural': 'Вотермарка'},
        ),
        migrations.AlterField(
            model_name='watermarkconfig',
            name='font_size',
            field=models.PositiveIntegerField(default=30, verbose_name='Размер шрифта'),
        ),
        migrations.AlterField(
            model_name='watermarkconfig',
            name='opacity',
            field=models.PositiveIntegerField(default=180, help_text='(0-255)', verbose_name='Прозрачность'),
        ),
        migrations.AlterField(
            model_name='watermarkconfig',
            name='position',
            field=models.CharField(choices=[('top_left', 'Слева сверху'), ('top_right', 'Справа сверху'), ('bottom_left', 'Слева снизу'), ('bottom_right', 'Справа снизу'), ('center', 'По центру')], default='bottom_right', max_length=20, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='watermarkconfig',
            name='text',
            field=models.CharField(default='©Aleucos', max_length=255, verbose_name='Текст'),
        ),
    ]
