# Generated by Django 5.1 on 2025-03-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Состав'),
        ),
    ]
