# Generated by Django 5.1 on 2025-04-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_is_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='will_arrive_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления (если в пути)'),
        ),
    ]
