# Generated by Django 5.1 on 2025-04-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_will_arrive_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default='', max_length=9, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Штрихкод'),
        ),
    ]
