# Generated by Django 5.1 on 2025-04-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='/static/img/default.png', upload_to='products', verbose_name='Фото'),
        ),
    ]
