# Generated by Django 5.1 on 2025-04-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['brand__title', 'title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='title_russian',
        ),
    ]
