# Generated by Django 5.1 on 2025-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_russian',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Русское название'),
        ),
    ]
